server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/mall?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: manager
    password: mk123456

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:cn/**/mapper/*.xml
